version: "3.7"
services:
    gateway:
        build:
            context: gateway/docker
            dockerfile: develop/nginx/Dockerfile
        ports:
            - "8080:8080"
            - "8081:8081"
        depends_on:
            - frontend
            - api

    frontend:
        build:
            context: frontend/docker
            dockerfile: develop/nginx/Dockerfile
        volumes:
            - ./frontend:/app

    api:
        build:
            context: api/docker
            dockerfile: develop/nginx/Dockerfile
        volumes:
            - ./api:/app
        depends_on:
            - api-php-fpm

    api-php-fpm:
        build:
            context: api/docker
            dockerfile: develop/php-fpm/Dockerfile
        environment:
            APP_ENV: dev
            APP_DEBUG: 1
            XDEBUG_MODE: debug
            XDEBUG_SESSION: 1
            PHP_IDE_CONFIG: serverName=slim_service
        volumes:
            - ./api:/app

    api-php-cli:
        build:
            context: api/docker
            dockerfile: develop/php-cli/Dockerfile
        environment:
            APP_ENV: dev
            APP_DEBUG: 1
            XDEBUG_MODE: debug
            XDEBUG_SESSION: 1
            PHP_IDE_CONFIG: serverName=slim_service
        volumes:
            - ./api:/app